--- 
services: 
  backend: 
    build: 
      context: backend
    image: "claratech/mybackend:1.0"
    volumes: 
      - "backend-var-log:/var/log"
  backendlog: 
    build: 
      context: awslogs
    depends_on: 
      - backend
    image: "claratech/backendlogs:1.0"
    volumes: 
      - "backend-var-log:/mnt/log"
  frontend: 
    build: 
      context: frontend
    depends_on: 
      - backend
    environment: 
      BACKENDLB: test
    image: "claratech/myfrontend:1.0"
    ports: 
      - "9000:80"
    volumes: 
      - "frontend-var-log:/var/log"
  frontendlog: 
    build: 
      context: awslogs
    depends_on: 
      - frontend
    image: "claratech/frontendlogs:1.0"
    volumes: 
      - "frontend-var-log:/mnt/log"
version: "3"
volumes: 
  backend-var-log: ~
  frontend-var-log: ~
